export const AppRoutes = {
  splash: "/",
  login: "/login",
  legacyLogin: "/lpgin",
  register: "/register",
  home: "/home",
  consultation: "/consultation",
  calculator: "/calculator",
  plantingGuide: "/planting-guide",
  weather: "/weather",
  notes: "/notes",
  noteDetail: (noteId: string) => `/notes/${noteId}`,
  noteEdit: (noteId: string) => `/notes/${noteId}/edit`,
  profile: "/profile",
  profilePersonalInfo: "/profile/personal-info",
  profileNotifications: "/profile/notifications",
  profilePrivacySecurity: "/profile/privacy-security",
} as const;
